# Generated by Django 4.0.5 on 2025-10-08 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('lat', models.DecimalField(decimal_places=15, default=0.0, max_digits=30)),
                ('lng', models.DecimalField(decimal_places=15, default=0.0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=10, unique=True)),
                ('index', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=2)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('map', models.ImageField(blank=True, upload_to='images')),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('travel_time', models.IntegerField(default=0)),
                ('avg_speed', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('status', models.CharField(default='F0F0F0', max_length=6)),
                ('end_point', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='end_point', to='roads.address')),
                ('route', models.ForeignKey(db_column='route', default=1, on_delete=django.db.models.deletion.PROTECT, to='roads.route')),
                ('start_point', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='start_point', to='roads.address')),
            ],
        ),
    ]
